import pytest
from api.products import get_product_details


def test_valid_products():
    mock_response = {
        "https://shop.lululemon.com/c/accessories/_/N-1z0xcmkZ1z0xl44Z8ok?format=json": [
            "Classic Unisex Ball Cap *Wordmark",
            "Men's Days Shade Ball Cap *Logo",
            "Men's Fast and Free Running Hat",
            "Fast and Free Running Hat",
            "Men's Days Shade Ball Cap",
            "Multi-Panel Hat",
            "Trucker Hat",
            "Classic Unisex Ball Cap",
            "Men's Fast and Free Running Hat",
            "High Ventilation Running Hat",
            "Drawcord Hiking Cap"
        ],
        "https://shop.lululemon.com/c/womens-leggings/_/N-8r6?format=json": [
            "Wunder Train High-Rise Tight 25\"",
            "lululemon Align™ High-Rise Pant 28\"",
            "Wunder Train High-Rise Tight 28\"",
            "lululemon Align™ High-Rise Pant 25\"",
            "lululemon Align™ High-Rise Mini-Flare Pant *Regular",
            "lululemon Align™ High-Rise Ribbed Pant 28\"",
            "lululemon Align™ High-Rise Pant with Pockets 25\"",
            "lululemon Align™ High-Rise Ribbed Pant 25\"",
            "lululemon Align™ High-Rise Crop 23\"",
            "Groove Super-High-Rise Flared Pant Nulu *Regular",
            "lululemon Align™ High-Rise Mini-Flared Pant *Extra Short",
            "lululemon Align™ High-Rise Crop 17\"",
            "Wunder Train High-Rise Tight with Pockets 25\"",
            "lululemon Align™ High-Rise Crop with Pockets 23\"",
            "Wunder Train Contour Fit High-Rise Tight 25\"",
            "lululemon Align™ Super-High-Rise Pant 28\"",
            "Wunder Train High-Rise Crop 23\"",
            "lululemon Align™ High-Rise Pant 31\"",
            "lululemon Align™ Ribbed Mini-Flare Pant *Extra Short",
            "lululemon Align™ High-Rise Ribbed Mini-Flare Pant *Regular",
            "Wunder Train High-Rise Crop with Pockets 23\"",
            "lululemon Align™ High-Rise Ribbed Crop 23\"",
            "Wunder Train High-Rise Crop 21\"",
            "Wunder Train Contour Fit High-Rise Crop 23\"",
            "lululemon Align™ Low-Rise Flared Pant 32.5\"",
            "lululemon Align™ Asymmetrical-Waist Mini-Flared Pant 32\"",
            "Wunder Train Contour Fit High-Rise Tight with Pockets 25\"",
            "lululemon Align™ Low-Rise Pant 25\"",
            "lululemon Align™ Mini-Flared Pant *Tall",
            "Wunder Train High-Rise Tight 31\"",
            "lululemon Align™ High-Rise Crop 21\"",
            "Wunder Under SmoothCover High-Rise Tight 25\"",
            "Wunder Train High-Rise Ribbed Tight 25\"",
            "Wunder Train High-Rise Ribbed Tight 28\"",
            "lululemon Align™ High-Rise Pant 28\" *Shine",
            "lululemon Align™ High-Rise Pant 25\" *Shine",
            "lululemon Align™ High-Rise Pant with Pockets 28\"",
            "lululemon Align™ V-Waist Mini-Flare Pant",
            "SenseKnit Running High-Rise Tight 28\"",
            "Wunder Train Contour Fit High-Rise Tight 28\"",
            "Wunder Under SmoothCover High-Rise Tight 28\"",
            "lululemon Align™ Asymmetrical-Waist Pant 25\"",
            "Fast and Free High-Rise Tight 25” Pockets *Updated",
            "Nulux Reflective High-Rise Track Tight 25\"",
            "Wunder Under SmoothCover Tight with Pockets 25\"",
            "Groove High-Rise Flared Pant with Pockets 32.5\"",
            "Fast and Free High-Rise Crop 23\" Pockets *Updated",
            "Wunder Train High-Rise Ribbed Crop 23\"",
            "Wunder Train Low-Rise Tight 25\"",
            "Wunder Train High-Rise Tight with Pockets 28\"",
            "Fast and Free High-Rise Tight 25\" *Colour Block",
            "Fast and Free High-Rise Tight 28” Pockets *Updated",
            "Fast and Free High-Rise Crop with Pockets 19\"",
            "lululemon Align™ V-Waist Pant 25\"",
            "lululemon Align™ High-Rise Crop 23\" *Shine",
            "Fast and Free High-Rise Thermal Tight 28\" *Pockets",
            "Fast and Free High-Rise Thermal Tight 25\" *Pockets",
            "lululemon Align™ High-Rise Pant with Pockets 31\"",
            "lululemon Align™ High-Rise Pant 28\"",
            "Fast and Free High-Rise Tight 25\"",
            "Swift Speed High-Rise Tight 28\"",
            "lululemon Align™ High-Rise Pant 25\"",
            "Groove Super-High-Rise Flared Pant Nulu *Regular",
            "Wunder Train High-Rise Tight 25\" *Foil",
            "Invigorate High-Rise Tight 25\"",
            "Wunder Train High-Rise Tight 28\" *Foil",
            "Base Pace High-Rise Tight 25\"",
            "Swift Speed High-Rise Crop 21\"",
            "lululemon Align™ High-Rise Pant with Pockets 25\"",
            "Swift Speed High-Rise Tight 28\" *Brushed Luxtreme",
            "lululemon Align™ High-Rise Mini-Flared Pant *Extra Short",
            "Wunder Train High-Rise Tight 28\"",
            "lululemon Align™ High-Rise Mini-Flared Pant *Regular",
            "lululemon Align™ High-Rise Ribbed Pant 25\"",
            "Wunder Train High-Rise Tight 25\"",
            "Fast and Free High-Rise Tight 25” Pockets *Updated",
            "Wunder Train High-Rise Crop 23\" *Foil",
            "lululemon Align™ High-Rise Pant with Pockets 28\"",
            "Base Pace High-Rise Crop 23\"",
            "Wunder Train High-Rise Crop 23\"",
            "Wunder Train Mesh High-Rise Tight 25\"",
            "lululemon Align™ High-Rise Crop 21\"",
            "lululemon Align™ High-Rise Ribbed Mini-Flared Pant *Regular",
            "lululemon Align™ High-Rise Ribbed Pant 28\"",
            "Fast and Free High-Rise Crop 23\"",
            "lululemon Align™ Asymmetrical-Waist Mini-Flared Pant 32\"",
            "Wunder Train Contour Fit High-Rise Tight 28\"",
            "Wunder Under High-Rise Tight 25\" *Shine",
            "lululemon Align™ High-Rise Crop 23\"",
            "Wunder Train High-Rise Tight with Pockets 25\"",
            "All the Right Places High-Rise Drawcord Waist Crop 23”",
            "lululemon Align™ High-Rise Ribbed Mini-Flared Pant *Extra Short",
            "lululemon Align™ Asymmetrical-Waist Pant 25\"",
            "lululemon Align™ Low-Rise Pant 25\"",
            "Fast and Free High-Rise Crop 19\"",
            "Fast and Free High-Rise Fleece Tight 28\"",
            "High-Rise Base Layer Tight 28\"",
            "lululemon Align™ High-Rise Mini-Flared Pant *Extra Short",
            "lululemon Align™ V-Waist Pant 25\"",
            "lululemon Align™ High-Rise Ribbed Pant 28\" *Shine",
            "Cargo Super-High-Rise Hiking Tight 25\"",
            "lululemon Align™ High-Rise Wide-Leg Pant *Short",
            "Wunder Train Aerobic High-Rise Tight 25\" *Twill",
            "InStill High-Rise Tight 25\"",
            "Cold Weather High-Rise Running Tight 28\"",
            "Groove Super-High-Rise Crop 23\" *Nulu",
            "SenseKnit Running High-Rise Tight 28\"",
            "lululemon Align™ High-Rise Wide-Leg Pant *Regular",
            "Merino Wool-Blend Base Layer Tight 28\"",
            "V-Waist Yoga Tight 25\" *Grid Texture",
            "SenseKnit High-Rise Running Tight 28\"",
            "lululemon Align™ High-Rise Pant 25\" *Shine",
            "Everlux and Mesh Super-High-Rise Training Tight 25\"",
            "lululemon lab Embossed Nulu Yoga Tight 25\"",
            "Keep the Heat Thermal High-Rise Tight 28\" *Colourblock"
        ]
    }
    response = get_product_details()
    assert isinstance(response, dict)
    assert response == mock_response
